export const concreteWorksTracker = [
  "01. PRE POUR INSPECTION [PRE POUR CONCRETE CHECKSHEET]",
  "02. TEMPORARY WORKS [PERMIT TO LOAD]",
  "03. CAST CONCRETE POUR HISTORY SHEET [POUR HISTORY CHECKSHEET]",
  "04. TEMPORARY WORKS [PERMIT TO UNLOAD]",
  "05. POST POUR INSPECTION [POST POUR CONCRETE CHECKSHEET]",
  "06. AS BUILT SURVEY COMPLETED",
  "07. CONCRETE COVER METRE SURVEY COMPLETED",
  "08. REDLINE DRAWINGS (WSP, CADS, KASHEC ETC DRAWINGS MARKED UP ON ASITE)",
  "09. ELEMENT COMPLETE (ALL NCRS AND SNAGS CLOSED OUT)",
];

export const waterproofing = [
  "01. PRE POUR INSPECTION [PRE POUR CONCRETE CHECKSHEET]",
  "02. TEMPORARY WORKS [PERMIT TO LOAD]",
  "03. CAST CONCRETE POUR HISTORY SHEET [POUR HISTORY CHECKSHEET]",
  "04. TEMPORARY WORKS [PERMIT TO UNLOAD]",
  "05. POST POUR INSPECTION [POST POUR CONCRETE CHECKSHEET]",
  "06. WATERPROOFING [WATERPROOFING CHECKSHEET]",
  "07. AS BUILT SURVEY COMPLETED",
  "08. BACKFILLING [EARTHWORKS SURVEILLANCE RECORD]",
  "09. REDLINE DRAWINGS (WSP, CADS, KASHEC ETC DRAWINGS MARKED UP ON ASITE)",
  "10. ELEMENT COMPLETE (ALL NCRS AND SNAGS CLOSED OUT)",
];
