const tasksFilter = [
  { id: "ft01", name: "REF",type:" ", data:[]  },
  { id: "ft02", name: "LOCATION",type:" ", data:[]  },
  { id: "ft03", name: "TASK DESCRIPTION",type:" ", data:[]  },
  {
    id: "ft04",
    name: "STATUS",
    type: "checkbox",
    data: [
      "All Open",
      "All Non Complete",
      "All Complete",
      "All Closed",
      "Completed",
      "Opened",
      "Signed Off",
    ],
  },
  // { id: "ft05", name: "TASK TYPE" },
  // { id: "ft06", name: "ISSUED TO PACKAGE" },
  // { id: "ft07", name: "ISSUED TO USER" },
  // { id: "ft08", name: "ISSUED TO ORGANISATION" },
  // { id: "ft09", name: "ISSUED BY ORGANISATION" },
  // { id: "ft10", name: "ISSUED BY USER" },
  // { id: "ft11", name: "SHOW OVERDUE TASKS ONLY" },
  // { id: "ft12", name: "CREATED/ISSUED DATE" },
  // { id: "ft13", name: "STATUS CHANGE DATE" },
  // { id: "ft14", name: "SCORES" },
  // { id: "ft15", name: "PRIORITIES" },
  // { id: "ft16", name: "CAUSED BY ORGANISATION" },
  // { id: "ft17", name: "CAUSES" },
  // { id: "ft18", name: "LOCATION CLASSIFICATIONS" },
  // { id: "ft19", name: "IMAGES" },
  // { id: "ft20", name: "DOCUMENTS" },
  // { id: "ft21", name: "COMMENTS" },
  // { id: "ft22", name: "ASSOCIATIONS" },
];

export default tasksFilter;
