const tasksColumnConfigList = [
  { id: "tccl01", name: "REF" },
  { id: "tccl02", name: "LOCATION" },
  { id: "tccl03", name: "TASK DESCRIPTION" },
  { id: "tccl04", name: "STATUS" },
  { id: "tccl05", name: "TASK TYPE" },
  { id: "tccl06", name: "ISSUED TO PACKAGE" },
  { id: "tccl07", name: "ISSUED TO USER" },
  { id: "tccl08", name: "ISSUED TO ORGANISATION" },
  { id: "tccl09", name: "ISSUED BY ORGANISATION" },
  { id: "tccl10", name: "ISSUED BY USER" },
  { id: "tccl11", name: "SHOW OVERDUE TASKS ONLY" },
  { id: "tccl12", name: "CREATED/ISSUED DATE" },
  { id: "tccl13", name: "STATUS CHANGE DATE" },
  { id: "tccl14", name: "SCORES" },
  { id: "tccl15", name: "PRIORITIES" },
  { id: "tccl16", name: "CAUSED BY ORGANISATION" },
  { id: "tccl17", name: "CAUSES" },
  { id: "tccl18", name: "LOCATION CLASSIFICATIONS" },
  { id: "tccl19", name: "IMAGES" },
  { id: "tccl20", name: "DOCUMENTS" },
  { id: "tccl21", name: "COMMENTS	" },
  { id: "tccl22", name: "ASSOCIATIONS" },
];
export default tasksColumnConfigList