const columnConfigList = [
  { id: "c00", name: "Ref" },
  { id: "c01", name: "Status" },
  { id: "c02", name: "Location" },
  { id: "c03", name: "Description" },
  { id: "c04", name: "Created" },
  { id: "c05", name: "Target" },
  { id: "c06", name: "Type" },
  { id: "c08", name: "To Organisation" },
  { id: "c09", name: "To User" },
  { id: "c10", name: "Tp Package" },
  { id: "c11", name: "To User" },
  { id: "c12", name: "By Organisation" },
  { id: "c13", name: "Status Changed" },
  // { id: "c14", name: "Associations" },
  // { id: "c15", name: "Overdue" },
  // { id: "c16", name: "Images" },
  { id: "c17", name: "Comments" },
  { id: "c18", name: "Documents" },
  { id: "c19", name: "Completed Date" },
  { id: "c20", name: "Completed By User" },
  { id: "c21", name: "Closed Date" },
  { id: "c22", name: "Closed By User" },
  // { id: "c23", name: "Priority" },
  { id: "c24", name: "Cause" },
  { id: "c25", name: "Caused By Organisation" },
  // { id: "c26", name: "Actual Start Date" },
  // { id: "c27", name: "Actual Finish Date" },
  // { id: "c28", name: "Cost" },
  // { id: "c29", name: "Percentage Complete" },
  // { id: "c30", name: "Planned Start Date" },
  // { id: "c31", name: "Remaining Duration" },
  // { id: "c32", name: "Resolution" },
  // { id: "c33", name: "Gps Accuracy" },
  // { id: "c34", name: "Gps Latitude" },
  // { id: "c35", name: "Gps Longitude" },
  // { id: "c36", name: "Score" },
  // { id: "c37", name: "Location Classification" },
];

export default columnConfigList;
