const listOfWidgets = [
    { type: "task", name: "Organizations With Most Tasks", image: "img" },
    { type: "task", name: "Location With Most Tasks", image: "img" },
    { type: "task", name: "Location With Most Tasks", image: "img" },
    { type: "task", name: "Overdue Task Count", image: "img" },
    { type: "task", name: "Recent Task Activity", image: "img" },
    { type: "task", name: "Task Type Overview", image: "img" },
    { type: "task", name: "Task Grouped By Organization Type", image: "img" },
    { type: "task", name: "Task Grouped By Task Type", image: "img" },
    { type: "task", name: "Task S Curve", image: "img" },
    { type: "forms", name: "Business Unit Form ByStatus", image: "img" },
    { type: "forms", name: "Expired Forms", image: "img" },
    { type: "forms", name: "Form Breakdown", image: "img" },
    { type: "forms", name: "Form Detail Grid", image: "img" },
    { type: "forms", name: "Form Detail Status", image: "img" },
    { type: "forms", name: "Form KPI", image: "img" },
    { type: "forms", name: "Form S Curve", image: "img" },
    { type: "forms", name: "Forms Issued By Month", image: "img" },
    { type: "forms", name: "Forms Recent Activity", image: "img" },
    { type: "forms", name: "Form Status", image: "img" },
    { type: "forms", name: "Forms Status By Month", image: "img" },
    { type: "forms", name: "Forms Works List ", image: "img" },
    { type: "processes", name: "Process Percentage Complete ", image: "img" },
  ];
  export default listOfWidgets