const assetsColumnConfigList = [
  { id: "accl01	", name: "Show/Hide All" },
  { id: "accl02", name: "Description" },
  { id: "accl03", name: "Status" },
  { id: "accl04", name: "Status Changed" },
  { id: "accl05", name: "Location" },
  { id: "accl06", name: "Code" },
  { id: "accl07", name: "Workflow" },
  { id: "accl08", name: "Parent Classification" },
  { id: "accl09", name: "Own Classification" },
  { id: "accl10", name: "Closed" },
  { id: "accl11", name: "Checked By User" },
  { id: "accl12", name: "Quantity" },
  { id: "accl13", name: "Open Tasks" },
  { id: "accl14", name: "Total Tasks" },
  { id: "accl15", name: "Open Forms" },
  { id: "accl16", name: "Total Forms" },
  { id: "accl17", name: "Associations" },
  { id: "accl18", name: "Images" },
  { id: "accl19", name: "Comments" },
  { id: "accl20", name: "Documents" },
];
export default assetsColumnConfigList